apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-count-deployment
  labels:
    app: pcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcd
  template:
    metadata:
      labels:
        app: pcd
    spec:
      containers:
      - name: pcd
        image: tahaq7869/zapata-test:0.1
        ports:
        - containerPort: 8888

--- 

apiVersion: v1
kind: Service
metadata:
  name: pcd-service
spec:
  selector:
    app: pcd
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
