apiVersion: v1
kind: ServiceAccount
metadata:
  name: zapata-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zapata-role
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - deployments
  - events
  - deployments/scale
  verbs:
  - "patch"
  - "list"
  - "get" 
  - "create"
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zapata-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zapata-role
subjects:
- kind: ServiceAccount                                  
  name:  zapata-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zapata-cluster-role
rules:
- apiGroups: ["zapata.test.com"]
  resources: ["*"]
  verbs: ["*"]

---
   
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zapata-cluster-binding
subjects:
- kind: ServiceAccount 
  namespace: test
  name: zapata-operator
roleRef:
  kind: ClusterRole
  name: zapata-cluster-role
  apiGroup: rbac.authorization.k8s.io

