apiVersion: v1
kind: ServiceAccount
metadata:
  name: zscaler-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zscaler-operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - zapata.test.com
    resources:
      - zscalers
      - zscalers/status
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zscaler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zscaler-operator
subjects:
  - kind: ServiceAccount
    name: zscaler-operator
