apiVersion: zapata.test.com/v1
kind: ZScaler
metadata:
  name: nginx-request-autoscaler
spec:
  deploymentName: nginx-deployment
  serviceName: pcd-service
  minReplicas: 1
  maxReplicas: 4
  scaleUpThreshold: 50
  scaleDownThreshold: 20
